Added nav links
StoneGod/TaskManager pull request #11
Opened 2020-06-09 16:17 UTC by StoneGod

2020-06-09 20:35 UTC, Andrew8xx8 requested changes

2020-06-09 20:35 UTC, Andrew8xx8 commented on config/puma.rb
> +port        ENV.fetch("PORT") { 8080 }
Зачем менять порт по умлочанию, если можно задать его через переменные окружения

2020-06-10 04:22 UTC, StoneGod commented on config/puma.rb
> +port        ENV.fetch("PORT") { 8080 }
В задание было написано, вот и подумал а почему бы и нет

2020-06-12 11:55 UTC, pn-y approved these changes

2020-06-12 12:22 UTC, merged