Added task api
StoneGod/TaskManager pull request #13
Opened 2020-06-12 13:44 UTC by StoneGod

2020-06-14 18:24 UTC, artempartos requested changes

2020-06-14 18:24 UTC, artempartos commented on test/controllers/api/v1/tasks_controller_test.rb
> +    author = create(:user)
добавь в тест assert_differences, что у тебя прибавился один пользователь

2020-06-14 18:24 UTC, artempartos commented on test/controllers/api/v1/tasks_controller_test.rb
> +    author = create(:user)
а здесь что убавился

2020-06-16 14:35 UTC, StoneGod commented on test/controllers/api/v1/tasks_controller_test.rb
> +    author = create(:user)
Хмм, а зачем в тесте на создание задачи тестировать создание пользователя.
Лучше добавлю assert_differences на то что задача создалась

2020-06-16 14:39 UTC, StoneGod commented on test/controllers/api/v1/tasks_controller_test.rb
> +    author = create(:user)
Тут тоже добавил проверку на удаление задачи.

2020-06-16 15:28 UTC, pn-y requested changes

2020-06-16 15:28 UTC, pn-y commented on app/controllers/api/v1/tasks_controller.rb
> +    params.require(:task).permit(:name, :description, :author_id, :assignee_id, :state_event)
Автора нельзя менять

2020-06-30 18:55 UTC, pn-y approved these changes

2020-07-01 02:56 UTC, merged