Added validation on models User and Task
StoneGod/TaskManager pull request #6
Opened 2020-06-05 05:30 UTC by StoneGod

2020-06-05 12:03 UTC, pn-y requested changes

2020-06-05 12:03 UTC, pn-y commented on app/models/user.rb
> +  validates :email, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
Добавь еще уникальный индекс, чтоб обеспечить целостность данных на уровне бд

2020-06-08 12:17 UTC, StoneGod commented on app/models/user.rb
> +  validates :email, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
Окей, заодно тогда и `not null` досыплю

2020-06-09 20:27 UTC, Andrew8xx8 approved these changes

2020-06-12 12:08 UTC, merged