Added state_machine for task
StoneGod/TaskManager pull request #7
Opened 2020-06-08 17:29 UTC by StoneGod

2020-06-09 20:29 UTC, Andrew8xx8 requested changes

2020-06-09 20:29 UTC, Andrew8xx8 commented on app/models/task.rb
> +  state_machine initial: :new_task do
Добавь список всех стейтов в начале

2020-06-10 04:08 UTC, StoneGod commented on app/models/task.rb
> +  state_machine initial: :new_task do
Поправил

2020-06-12 11:51 UTC, pn-y requested changes

2020-06-12 11:51 UTC, pn-y commented on app/models/task.rb
> +  state_machine initial: :new_task do
Все еще не вижу всех доступных стейтов в начале

2020-06-12 11:51 UTC, pn-y commented on db/migrate/20200608172350_change_task_default_state.rb
> +    change_column :tasks, :state, :string, null: false, default: :new_task
Не размазывай логику между приложением и базой. Убери проверки и дефолтные значения.

2020-06-12 11:56 UTC, StoneGod commented on app/models/task.rb
> +  state_machine initial: :new_task do
Хмм, я не понял что за список доступных стейтов

2020-06-12 12:02 UTC, StoneGod commented on app/models/task.rb
> +  state_machine initial: :new_task do
> Все еще не вижу всех доступных стейтов в начале

это или валидация на доступные значения, либо комментарий из стендов что могут быть, других идей что за список такой у меня нету

2020-06-12 12:21 UTC, StoneGod commented on app/models/task.rb
> +  state_machine initial: :new_task do
А я похоже dsl не догнал(

2020-06-12 13:15 UTC, pn-y approved these changes

2020-06-12 13:16 UTC, merged