Added session controller
StoneGod/TaskManager pull request #9
Opened 2020-06-09 15:51 UTC by StoneGod

2020-06-09 20:32 UTC, Andrew8xx8 requested changes

2020-06-09 20:32 UTC, Andrew8xx8 commented on app/forms/session_form.rb
> +  def user_valid?
Тут хорошо бы подумать над названием метода, название говорит о том, что валидный ли юзер, а проверяются на самом деле его данные для логина или если по английски `credentials`

2020-06-12 11:55 UTC, pn-y requested changes

2020-06-12 11:55 UTC, pn-y commented on app/models/user.rb
> +  validates :email, uniqueness: true, email: true
Добавь уникальный индекс для консистентности базы

2020-06-12 11:59 UTC, StoneGod commented on app/models/user.rb
> +  validates :email, uniqueness: true, email: true
Так он есть в ПР https://github.com/StoneGod/TaskManager/pull/6/files#diff-1acd2e7e27a227829d5d14a91c863bb6R38

2020-06-12 13:18 UTC, pn-y requested changes

2020-06-12 13:18 UTC, pn-y commented on test/controllers/web/developers_controller_test.rb
> +    assert_response :redirect
Если из контроллера выпилить все кроме редиректа - тест продолжит работать.

2020-06-12 13:30 UTC, StoneGod commented on test/controllers/web/developers_controller_test.rb
> +    assert_response :redirect
Поправил

2020-06-12 13:35 UTC, pn-y approved these changes

2020-06-12 13:36 UTC, merged